server:
  port: 8090
spring:
  application:
    name: loans
  profiles:
    active: "prod" # use "prod" profile by default
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8071}"
    fail-fast: true # retry if configserver not ready
    retry:
      max-attempts: 6
      initial-interval: 2000 # ms
      multiplier: 1.5
      max-interval: 10000 # ms
    cloud:
      bus:
        enabled: true
      stream:
        kafka:
          binder:
            brokers: ${KAFKA_BROKER_URL:localhost:9092}
  management:
    endpoints:
      web:
        exposure:
          include: health,info,bus-refresh # or just "refresh" if you want to be strict
