services:
  configserver:
    build:
      context: ./configserver
      dockerfile: Dockerfile
    container_name: configserver
    ports:
      - "8071:8071"
    environment:
      - KAFKA_BROKER_URL=kafka:29092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - easybank-net

  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy

    environment:
      - CONFIG_SERVER_URL=http://configserver:8071
      - KAFKA_BROKER_URL=kafka:29092
    networks:
      - easybank-net

  loans:
    build:
      context: ./loans
      dockerfile: Dockerfile
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      - CONFIG_SERVER_URL=http://configserver:8071
      - KAFKA_BROKER_URL=kafka:29092
    networks:
      - easybank-net

  cards:
    build:
      context: ./cards
      dockerfile: Dockerfile
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      - CONFIG_SERVER_URL=http://configserver:8071
      - KAFKA_BROKER_URL=kafka:29092
    networks:
      - easybank-net

networks:
  easybank-net:
    external: true
