version: "3.9"

services:
  configserver:
    build:
      context: ./configserver
      dockerfile: Dockerfile
    container_name: configserver
    ports:
      - "8071:8071"
    networks:
      - easybank-net

  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      - configserver
    environment:
      - CONFIG_SERVER_URL=http://configserver:8071
    networks:
      - easybank-net

  loans:
    build:
      context: ./loans
      dockerfile: Dockerfile
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      - configserver
    environment:
      - CONFIG_SERVER_URL=http://configserver:8071
    networks:
      - easybank-net

  cards:
    build:
      context: ./cards
      dockerfile: Dockerfile
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      - configserver
    environment:
      - CONFIG_SERVER_URL=http://configserver:8071
    networks:
      - easybank-net

networks:
  easybank-net:
    driver: bridge
